// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos-cash/verifiable-credential/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryVerifiableCredentialsRequest is request type for Query/VerifiableCredentials RPC method.
type QueryVerifiableCredentialsRequest struct {
	// status enables to query for credentials matching a given status.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryVerifiableCredentialsRequest) Reset()         { *m = QueryVerifiableCredentialsRequest{} }
func (m *QueryVerifiableCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVerifiableCredentialsRequest) ProtoMessage()    {}
func (*QueryVerifiableCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74876a0b18172cc7, []int{0}
}
func (m *QueryVerifiableCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifiableCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifiableCredentialsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifiableCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifiableCredentialsRequest.Merge(m, src)
}
func (m *QueryVerifiableCredentialsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifiableCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifiableCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifiableCredentialsRequest proto.InternalMessageInfo

func (m *QueryVerifiableCredentialsRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryVerifiableCredentialsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryVerifiableCredentialsResponse is response type for the Query/Identifers RPC method
type QueryVerifiableCredentialsResponse struct {
	// validators contains all the queried validators.
	Vcs []VerifiableCredential `protobuf:"bytes,1,rep,name=vcs,proto3" json:"vcs"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryVerifiableCredentialsResponse) Reset()         { *m = QueryVerifiableCredentialsResponse{} }
func (m *QueryVerifiableCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVerifiableCredentialsResponse) ProtoMessage()    {}
func (*QueryVerifiableCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74876a0b18172cc7, []int{1}
}
func (m *QueryVerifiableCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifiableCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifiableCredentialsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifiableCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifiableCredentialsResponse.Merge(m, src)
}
func (m *QueryVerifiableCredentialsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifiableCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifiableCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifiableCredentialsResponse proto.InternalMessageInfo

func (m *QueryVerifiableCredentialsResponse) GetVcs() []VerifiableCredential {
	if m != nil {
		return m.Vcs
	}
	return nil
}

func (m *QueryVerifiableCredentialsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryVerifiableCredentialRequest is response type for the Query/VerifiableCredential RPC method
type QueryVerifiableCredentialRequest struct {
	// verifiable_credential_id defines the credential id to query for.
	VerifiableCredentialId string `protobuf:"bytes,1,opt,name=verifiable_credential_id,json=verifiableCredentialId,proto3" json:"verifiable_credential_id,omitempty"`
}

func (m *QueryVerifiableCredentialRequest) Reset()         { *m = QueryVerifiableCredentialRequest{} }
func (m *QueryVerifiableCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVerifiableCredentialRequest) ProtoMessage()    {}
func (*QueryVerifiableCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74876a0b18172cc7, []int{2}
}
func (m *QueryVerifiableCredentialRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifiableCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifiableCredentialRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifiableCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifiableCredentialRequest.Merge(m, src)
}
func (m *QueryVerifiableCredentialRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifiableCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifiableCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifiableCredentialRequest proto.InternalMessageInfo

func (m *QueryVerifiableCredentialRequest) GetVerifiableCredentialId() string {
	if m != nil {
		return m.VerifiableCredentialId
	}
	return ""
}

// QueryVerifiableCredentialResponse is response type for the Query/VerifiableCredential RPC method
type QueryVerifiableCredentialResponse struct {
	// verifiable_credential defines the the credential info.
	VerifiableCredential VerifiableCredential `protobuf:"bytes,1,opt,name=verifiable_credential,json=verifiableCredential,proto3" json:"verifiable_credential"`
}

func (m *QueryVerifiableCredentialResponse) Reset()         { *m = QueryVerifiableCredentialResponse{} }
func (m *QueryVerifiableCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVerifiableCredentialResponse) ProtoMessage()    {}
func (*QueryVerifiableCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74876a0b18172cc7, []int{3}
}
func (m *QueryVerifiableCredentialResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifiableCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifiableCredentialResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifiableCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifiableCredentialResponse.Merge(m, src)
}
func (m *QueryVerifiableCredentialResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifiableCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifiableCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifiableCredentialResponse proto.InternalMessageInfo

func (m *QueryVerifiableCredentialResponse) GetVerifiableCredential() VerifiableCredential {
	if m != nil {
		return m.VerifiableCredential
	}
	return VerifiableCredential{}
}

// QueryVerifiableCredentialResponse is response type for the Query/VerifiableCredential RPC method
type QueryValidateVerifiableCredentialResponse struct {
	// is_valid defines if the credential is signed by the correct public key.
	IsValid bool `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
}

func (m *QueryValidateVerifiableCredentialResponse) Reset() {
	*m = QueryValidateVerifiableCredentialResponse{}
}
func (m *QueryValidateVerifiableCredentialResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryValidateVerifiableCredentialResponse) ProtoMessage() {}
func (*QueryValidateVerifiableCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74876a0b18172cc7, []int{4}
}
func (m *QueryValidateVerifiableCredentialResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidateVerifiableCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidateVerifiableCredentialResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidateVerifiableCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidateVerifiableCredentialResponse.Merge(m, src)
}
func (m *QueryValidateVerifiableCredentialResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidateVerifiableCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidateVerifiableCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidateVerifiableCredentialResponse proto.InternalMessageInfo

func (m *QueryValidateVerifiableCredentialResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func init() {
	proto.RegisterType((*QueryVerifiableCredentialsRequest)(nil), "allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsRequest")
	proto.RegisterType((*QueryVerifiableCredentialsResponse)(nil), "allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialsResponse")
	proto.RegisterType((*QueryVerifiableCredentialRequest)(nil), "allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialRequest")
	proto.RegisterType((*QueryVerifiableCredentialResponse)(nil), "allinbits.cosmoscash.verifiablecredential.QueryVerifiableCredentialResponse")
	proto.RegisterType((*QueryValidateVerifiableCredentialResponse)(nil), "allinbits.cosmoscash.verifiablecredential.QueryValidateVerifiableCredentialResponse")
}

func init() {
	proto.RegisterFile("cosmos-cash/verifiable-credential/query.proto", fileDescriptor_74876a0b18172cc7)
}

var fileDescriptor_74876a0b18172cc7 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0x6a, 0x13, 0x41,
	0x1c, 0xc6, 0xb3, 0x69, 0xad, 0x75, 0x7a, 0x1b, 0xd2, 0x12, 0x83, 0xac, 0x71, 0x0f, 0x9a, 0x0a,
	0xd9, 0xa1, 0x11, 0xb4, 0x17, 0x15, 0x5a, 0xa8, 0x88, 0x15, 0xcc, 0x0a, 0x16, 0x45, 0x08, 0xb3,
	0xbb, 0xe3, 0x76, 0x60, 0x77, 0x67, 0x9b, 0xff, 0x64, 0xb5, 0x8a, 0x17, 0xbd, 0x2a, 0x08, 0x3e,
	0x80, 0x6f, 0x23, 0x3d, 0x16, 0xbc, 0x78, 0x12, 0x49, 0x7c, 0x04, 0x1f, 0x40, 0x76, 0x67, 0x93,
	0x55, 0x98, 0x24, 0x2a, 0xb9, 0xcd, 0x0e, 0xf3, 0x7d, 0xf3, 0xfd, 0xbe, 0x99, 0x1d, 0xd4, 0xf6,
	0x04, 0x44, 0x02, 0xda, 0x1e, 0x85, 0x43, 0x92, 0xb2, 0x3e, 0x7f, 0xc6, 0xa9, 0x1b, 0xb2, 0xb6,
	0xd7, 0x67, 0x3e, 0x8b, 0x25, 0xa7, 0x21, 0x39, 0x1a, 0xb0, 0xfe, 0xb1, 0x9d, 0xf4, 0x85, 0x14,
	0x78, 0x93, 0x86, 0x21, 0x8f, 0x5d, 0x2e, 0xc1, 0x56, 0xc2, 0x4c, 0x67, 0x97, 0xba, 0x52, 0xd6,
	0xb8, 0x10, 0x08, 0x11, 0x84, 0x8c, 0xd0, 0x84, 0x13, 0x1a, 0xc7, 0x42, 0x52, 0xc9, 0x45, 0x0c,
	0xca, 0xa8, 0x71, 0x55, 0xc9, 0x89, 0x4b, 0x81, 0xa9, 0x1d, 0x48, 0xba, 0xe5, 0x32, 0x49, 0xb7,
	0x48, 0x42, 0x03, 0x1e, 0xe7, 0x8b, 0x8b, 0xb5, 0x37, 0xe7, 0x67, 0xd4, 0xce, 0x16, 0xf2, 0x5a,
	0x20, 0x02, 0x91, 0x0f, 0x49, 0x36, 0x52, 0xb3, 0xd6, 0x5b, 0x03, 0x5d, 0xea, 0x66, 0xfb, 0x3e,
	0x9a, 0x48, 0x77, 0x27, 0x4a, 0x70, 0xd8, 0xd1, 0x80, 0x81, 0xc4, 0x1b, 0x68, 0x05, 0x24, 0x95,
	0x03, 0xa8, 0x1b, 0x4d, 0xa3, 0x75, 0xce, 0x29, 0xbe, 0xf0, 0x1e, 0x42, 0x65, 0xcc, 0x7a, 0xb5,
	0x69, 0xb4, 0xd6, 0x3a, 0x97, 0x8b, 0x4a, 0xec, 0x8c, 0xc9, 0x56, 0xad, 0x15, 0x4c, 0xf6, 0x03,
	0x1a, 0xb0, 0xc2, 0xd3, 0xf9, 0x4d, 0x69, 0x7d, 0x36, 0x90, 0x35, 0x2b, 0x05, 0x24, 0x22, 0x06,
	0x86, 0x0f, 0xd0, 0x52, 0xea, 0x65, 0x19, 0x96, 0x5a, 0x6b, 0x9d, 0xdb, 0xf6, 0x5f, 0x1f, 0x82,
	0xad, 0xb3, 0xdd, 0x59, 0x3e, 0xf9, 0x76, 0xb1, 0xe2, 0x64, 0x8e, 0xf8, 0x8e, 0x86, 0xe3, 0xca,
	0x5c, 0x0e, 0x95, 0xea, 0x0f, 0x90, 0xa7, 0xa8, 0x39, 0x95, 0x63, 0x5c, 0xe6, 0x36, 0xaa, 0x97,
	0x21, 0x7b, 0x65, 0xca, 0x1e, 0xf7, 0x8b, 0x7a, 0x37, 0x52, 0x8d, 0xfc, 0xae, 0x6f, 0x7d, 0x9a,
	0x75, 0x58, 0x93, 0x96, 0x5e, 0xa2, 0x75, 0xad, 0x7f, 0x6e, 0xbe, 0xb0, 0xde, 0x6a, 0xba, 0x8c,
	0xd6, 0x1e, 0xda, 0x54, 0x01, 0x69, 0xc8, 0x7d, 0x2a, 0xd9, 0xcc, 0xa0, 0xe7, 0xd1, 0x2a, 0x87,
	0x5e, 0x9a, 0x2d, 0xcd, 0xb3, 0xad, 0x3a, 0x67, 0x39, 0xe4, 0xca, 0xce, 0xfb, 0x65, 0x74, 0x26,
	0x37, 0xc2, 0x3f, 0x0d, 0xb4, 0xae, 0xbd, 0x15, 0x78, 0xff, 0x1f, 0x40, 0xe6, 0x5e, 0xf1, 0xc6,
	0xfd, 0x05, 0xb9, 0x29, 0x36, 0xeb, 0xd6, 0x9b, 0x2f, 0x3f, 0x3e, 0x56, 0xb7, 0xf1, 0x75, 0x32,
	0xb1, 0x25, 0x3a, 0xaf, 0x29, 0xb3, 0xf8, 0x5d, 0x15, 0xd5, 0x74, 0x3b, 0xe0, 0x7b, 0x8b, 0xc8,
	0x39, 0x86, 0xde, 0x5f, 0x8c, 0x59, 0xc1, 0xfc, 0x38, 0x67, 0x7e, 0x88, 0xbb, 0xff, 0xc7, 0x4c,
	0x5e, 0x4d, 0xfb, 0x2d, 0x5e, 0xef, 0x74, 0x4f, 0x86, 0xa6, 0x71, 0x3a, 0x34, 0x8d, 0xef, 0x43,
	0xd3, 0xf8, 0x30, 0x32, 0x2b, 0xa7, 0x23, 0xb3, 0xf2, 0x75, 0x64, 0x56, 0x9e, 0xdc, 0x08, 0xb8,
	0x3c, 0x1c, 0xb8, 0xb6, 0x27, 0x22, 0xb2, 0x2b, 0x20, 0x3a, 0xa0, 0x10, 0x91, 0xe7, 0x14, 0x22,
	0x9f, 0xbc, 0x98, 0xf2, 0x4a, 0xca, 0xe3, 0x84, 0x81, 0xbb, 0x92, 0x3f, 0x80, 0xd7, 0x7e, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x69, 0x6d, 0x90, 0x7c, 0xfb, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Identifers queries all validators that match the given status.
	VerifiableCredentials(ctx context.Context, in *QueryVerifiableCredentialsRequest, opts ...grpc.CallOption) (*QueryVerifiableCredentialsResponse, error)
	// VerifiableCredential queries validator info for given validator address.
	VerifiableCredential(ctx context.Context, in *QueryVerifiableCredentialRequest, opts ...grpc.CallOption) (*QueryVerifiableCredentialResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) VerifiableCredentials(ctx context.Context, in *QueryVerifiableCredentialsRequest, opts ...grpc.CallOption) (*QueryVerifiableCredentialsResponse, error) {
	out := new(QueryVerifiableCredentialsResponse)
	err := c.cc.Invoke(ctx, "/allinbits.cosmoscash.verifiablecredential.Query/VerifiableCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifiableCredential(ctx context.Context, in *QueryVerifiableCredentialRequest, opts ...grpc.CallOption) (*QueryVerifiableCredentialResponse, error) {
	out := new(QueryVerifiableCredentialResponse)
	err := c.cc.Invoke(ctx, "/allinbits.cosmoscash.verifiablecredential.Query/VerifiableCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Identifers queries all validators that match the given status.
	VerifiableCredentials(context.Context, *QueryVerifiableCredentialsRequest) (*QueryVerifiableCredentialsResponse, error)
	// VerifiableCredential queries validator info for given validator address.
	VerifiableCredential(context.Context, *QueryVerifiableCredentialRequest) (*QueryVerifiableCredentialResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) VerifiableCredentials(ctx context.Context, req *QueryVerifiableCredentialsRequest) (*QueryVerifiableCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifiableCredentials not implemented")
}
func (*UnimplementedQueryServer) VerifiableCredential(ctx context.Context, req *QueryVerifiableCredentialRequest) (*QueryVerifiableCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifiableCredential not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_VerifiableCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifiableCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifiableCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allinbits.cosmoscash.verifiablecredential.Query/VerifiableCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifiableCredentials(ctx, req.(*QueryVerifiableCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifiableCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifiableCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifiableCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allinbits.cosmoscash.verifiablecredential.Query/VerifiableCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifiableCredential(ctx, req.(*QueryVerifiableCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "allinbits.cosmoscash.verifiablecredential.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifiableCredentials",
			Handler:    _Query_VerifiableCredentials_Handler,
		},
		{
			MethodName: "VerifiableCredential",
			Handler:    _Query_VerifiableCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos-cash/verifiable-credential/query.proto",
}

func (m *QueryVerifiableCredentialsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifiableCredentialsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifiableCredentialsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifiableCredentialsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifiableCredentialsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifiableCredentialsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Vcs) > 0 {
		for iNdEx := len(m.Vcs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vcs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifiableCredentialRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifiableCredentialRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifiableCredentialRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerifiableCredentialId) > 0 {
		i -= len(m.VerifiableCredentialId)
		copy(dAtA[i:], m.VerifiableCredentialId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.VerifiableCredentialId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifiableCredentialResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifiableCredentialResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifiableCredentialResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.VerifiableCredential.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryValidateVerifiableCredentialResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidateVerifiableCredentialResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidateVerifiableCredentialResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsValid {
		i--
		if m.IsValid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryVerifiableCredentialsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifiableCredentialsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Vcs) > 0 {
		for _, e := range m.Vcs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifiableCredentialRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VerifiableCredentialId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifiableCredentialResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VerifiableCredential.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryValidateVerifiableCredentialResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsValid {
		n += 2
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryVerifiableCredentialsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifiableCredentialsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifiableCredentialsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifiableCredentialsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifiableCredentialsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifiableCredentialsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vcs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vcs = append(m.Vcs, VerifiableCredential{})
			if err := m.Vcs[len(m.Vcs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifiableCredentialRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifiableCredentialRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifiableCredentialRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifiableCredentialId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifiableCredentialId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifiableCredentialResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifiableCredentialResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifiableCredentialResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifiableCredential", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VerifiableCredential.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidateVerifiableCredentialResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidateVerifiableCredentialResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidateVerifiableCredentialResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsValid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsValid = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
